### ISSUE TITLE
Beautify README

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/json-hub#131]
* Enhance the README, make it prettier
* Add a table of contents pointing to headers and sub-headers in README

**Comment by subhangi2731** [comment]
can you please assign me this?

**Comment by GuptaTanisha** [comment]
May I work on this?

**Comment by adityabisoi** [comment]
@GuptaTanisha Are you working on this?

**Comment by shubhsardana29** [comment]
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by neetra** [comment]
I would like to work

**Comment by shubhsardana29** [comment]
@adityabisoi please rename the label GSSoC'22 to just GSSoC22 . No special characters in Labels. Otherwise, the leaderboard won't detect the same.
