### ISSUE TITLE
CI/CD for building and pushing docker image [GSSOC]

### ISSUE THREAD

**Issue by a7medayman6** [adityabisoi/json-hub#181]
**Describe the feature**
Build a CI Pipeline using GitHub Actions to build and push to DockerHub the docker image from Dockerfile when needed.

**Is your feature request related to a problem? Please describe.** :bulb:
No, just to make an easier continuous integration environment and make the docker image available on dockerhub for easier running locally or on server. 

**Describe the solution you'd like** :zap:
Build a pipeline that have at least two stages 
1. Build docker image from the existed Dockerfile
2. Push docker image to the registry [DockerHub](http://hub.docker.com/)

**Expected behavior**
on each commit or pull request, build and push docker image.

**Screenshots**
Pipeline Flowchart 

![CI Pipeline Flowchart](https://user-images.githubusercontent.com/50116921/120251816-ffea1500-c282-11eb-922d-c1b726238a6c.jpg)

**Are you working on this feature? (Yes/No)**
I would like to

**Comment by a7medayman6** [comment]
@adityabisoi Can you add docker hub credentials in the repo secrets please ? 
so I can reference them in the workflow file

**Comment by adityabisoi** [comment]
Sure, they are named `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN`

**Comment by a7medayman6** [comment]
@adityabisoi 
I have built the pipeline and made a pull request. 
pull request : #182

**Comment by a7medayman6** [comment]
please merge the latest commit which is where I fixed the credentials issue mentioned in this pull request #183
