### ISSUE TITLE
Design a LOGO

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/json-hub#184]
Design a new LOGO which reflects the aim of the application.

**Comment by Mariosyian** [comment]
Hello, just saw this issue while GitHub surfing. Now I'm no logo designer but thought it'd be fun to give it a shot. The picture is a 1000x1000 pixel @ 300ppi
![json_hub](https://user-images.githubusercontent.com/10303302/154816085-ee95fe20-1f2b-4f9c-8487-dbcae1e36fc8.jpg)

It's meant to be an actual hub made by two curly braces, with the lines at the bottom being the ports.
The braces and the ports are `Sans-serif`, and the Json Hub text is `Arial Condensed`.

**Comment by adityabisoi** [comment]
Hi, @Mariosyian great work with the logo! I'll add it to the project. Thank you.
