### ISSUE TITLE
Make endpoints clickable

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/json-hub#185]
**Describe the bug -**
Make endpoint methods clickable.

Ex: Clicking on `GET /photos/`, the endpoint must open in a new tab, with the URI `http://localhost:5000/photos/`

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by Gurdeep475** [comment]
@adityabisoi one way i can think of to wrap the endpoints with an a tag, any suggestions from your side?
