### ISSUE TITLE
Add option to fetch data online

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/json-hub#186]
On the homepage, add an option with a fixed endpoint, such as `fetch(<endpoint>)`, which on clicking a `Execute` button, would fetch data from the particular endpoint and display it on the page. 

This would serve as an example of how to use the service properly in a project.

**Comment by Shivansh-yadav13** [comment]
I would like to contribute :)

**Comment by Shivansh-yadav13** [comment]
@adityabisoi what endpoint should I use?

**Comment by adityabisoi** [comment]
> @adityabisoi what endpoint should I use?

First try with one endpoint, and then make a PR.

**Comment by adityabisoi** [comment]
@Shivansh-yadav13 Updates on this issue?

**Comment by Shivansh-yadav13** [comment]
@adityabisoi really sorry can you assign this to other contributors, I won't be able to work on this rn.

**Comment by vakshit** [comment]
I can work on it. I just need to add a "Try out" button on the homepage so that the user can test the specific endpoint, right?

**Comment by adityabisoi** [comment]
@vakshit Correct. Assigning to you

**Comment by vakshit** [comment]
okay.. working on it.

**Comment by navyasharma0203** [comment]
@adityabisoi Can I work on this...if not yet closed...

**Comment by adityabisoi** [comment]
@navyasharma0203 Please go ahead. Bumping the level to level 3
